name: 'Splitsh'

author: 'Antal Áron <antalaron@antalaron.hu>'

description: 'Synchronises a subtree repository using splitsh-lite'

inputs:
    split:
        description: 'Full name of the subtree repository (e.g. owner/repository)'
        required: false
    split_deploy_key:
        description: 'Deploy key for the subtree repository'
        required: false
    split_branch:
        description: 'Branch name to split'
        required: false
    split_prefix:
        description: 'Prefix for the split'
        required: true
    split_only_if:
        description: 'Origin name, 0, or 1'
        required: true

runs:
    using: 'docker'
    image: 'Dockerfile'

branding:
    icon: git-branch
    color: green
